### PR TITLE
Use of Snmalloc C api for python

### PR DESCRIPTION
**Pull request by ryancinsight**
This is with the addition of snmalloc C API access to rust allowing python to integrate directly. pull request has been merged to snmalloc for these additions https://github.com/microsoft/snmalloc/pull/290 to rust.cc and to  to snmalloc-rs https://github.com/SchrodingerZhu/snmalloc-rs/pull/115.

### CODE REVIEW

**Comment by ryancinsight** [comment]
I'll push again when snmalloc_rs does a version bump

**Review by indygreg — CHANGES_REQUESTED** [review]
This looks good. But is failing CI because it needs a newer version of the `snmalloc_sys` crate.

Also, I believe you'll want to rename the `ctx` argument to `_ctx` in the changed functions to prevent a compiler warning about unused arguments.

I guess I'll wait on the new crate version before this merged.

Thank you for following up and getting the snmalloc changes made upstream!

**Comment by ryancinsight** [comment]
@indygreg and @mjp41 while we wait for snmalloc-rs version bump I ran some local tests using the below code and timed some processes with mimalloc and snmalloc for python raw allocator and python optimized pymalloc allocator. There does appear to be a clear difference with pymalloc being replaced with snmalloc performing significantly better with direct access to C API. I might try seeing if changing the global allocator has any effect, there was minor on snmalloc for large allocations. 

Indygreg, One option I think we should explore is mixed allocators, mimalloc for raw and snmalloc for pymalloc, the way it is now we are limited to 1 custom allocator and it looks like snmalloc may be better for these smaller allocations.

```import threading
import time
import timeit
from functools import wraps
import pprint
# Capture program start time
start_time = time.perf_counter()

thread_pool = list()                  # container to hold threads
total_delay = 0
thread_time_map = dict()
duration_from_decorator = 0


# container with random int (5, 20)
delay_index = [200000, 400000, 800000, 1600000, 3200000, 6400000, 12800000, 25600000, 51200000, 100000000]


def thread_time_decorator(thread):
    @wraps(thread)
    def wrapper(*args, **kwargs):
        start = time.perf_counter()
        thread(*args, **kwargs)
        end = time.perf_counter()
        threading.current_thread().thread_duration = end - start
    return wrapper


def worker(delay: int) -> None:
    time = timeit.timeit(f'"-".join([str(n) for n in range({delay})])', number=3)
    print(f"Worker_{delay} took {time} secs to complete")


for i in range(len(delay_index)):
    _delay = delay_index[i]
    total_delay += _delay
    wrapped_worker = thread_time_decorator(worker)
    t = threading.Thread(target=wrapped_worker, args=(_delay,), name=f'Worker_{_delay}')
    thread_pool.append(t)

for _thread in thread_pool:
    _thread.start()
    print(f'--- Started {_thread.name}')

for _thread in thread_pool:
    _thread.join()
    print(f'--- Completed {_thread.name}')
    print(f'{_thread.name} took {_thread.thread_duration} secs ')
    duration_from_decorator += _thread.thread_duration
    thread_time_map[_thread.name] = _thread.thread_duration
thread_time_map['Total sum'] = sum(thread_time_map.values())
thread_time_map['Total No of threads'] = len(thread_pool)
thread_time_map['Average thread time'] = thread_time_map['Total No of threads'] / len(thread_pool)
# dump stats to file
# Capture program end time
end_time = time.perf_counter()
execution_time = end_time - start_time


print(f'Total execution time: {execution_time} secs')
print(f'Total no of threads: {len(thread_pool)}')
print(f'Average time: {execution_time / len(thread_pool)}')
print(f'Decorated Threads total duration: {duration_from_decorator}')
print(f'Decorated Average: {duration_from_decorator / len(thread_pool)}')
pprint.pprint(thread_time_map)```

**System**
Total execution time: 132.47639519999998 secs
Total no of threads: 10
Average time: 13.247639519999998
Decorated Threads total duration: 368.19136590000005
Decorated Average: 36.81913659000001
{'Average thread time': 1.0,
 'Total No of threads': 10,
 'Total sum': 368.19136590000005,
 'Worker_100000000': 129.9253631,
 'Worker_12800000': 35.557990999999994,
 'Worker_1600000': 5.4281289,
 'Worker_200000': 0.3117568,
 'Worker_25600000': 61.6220786,
 'Worker_3200000': 10.328251,
 'Worker_400000': 1.3857203,
 'Worker_51200000': 97.35714660000001,
 'Worker_6400000': 22.8751338,
 'Worker_800000': 3.3997957999999997}

**python_config.allocator_backend = "snmalloc"**
Total execution time: 132.4186613 secs
Total no of threads: 10
Average time: 13.24186613
Decorated Threads total duration: 367.3834362
Decorated Average: 36.73834362
{'Average thread time': 1.0,
 'Total No of threads': 10,
 'Total sum': 367.3834362,
 'Worker_100000000': 129.94874950000002,
 'Worker_12800000': 37.5268716,
 'Worker_1600000': 5.7622406,
 'Worker_200000': 0.332735,
 'Worker_25600000': 62.298875599999995,
 'Worker_3200000': 11.2369783,
 'Worker_400000': 1.0873773,
 'Worker_51200000': 96.63881359999999,
 'Worker_6400000': 20.4619101,
 'Worker_800000': 2.0888845999999996}

**python_config.allocator_backend = "snmalloc"**
**python_config.allocator_pymalloc_arena = True**
Total execution time: 116.28005350000001 secs
Total no of threads: 10
Average time: 11.62800535
Decorated Threads total duration: 330.127746
Decorated Average: 33.0127746
{'Average thread time': 1.0,
 'Total No of threads': 10,
 'Total sum': 330.127746,
 'Worker_100000000': 114.1543368,
 'Worker_12800000': 37.3822548,
 'Worker_1600000': 4.6652109,
 'Worker_200000': 0.38535010000000003,
 'Worker_25600000': 54.5231522,
 'Worker_3200000': 9.9362132,
 'Worker_400000': 0.7333081,
 'Worker_51200000': 85.2805015,
 'Worker_6400000': 20.7775057,
 'Worker_800000': 2.2899127}

**python_config.allocator_backend = "mimalloc"**
Total execution time: 128.7653104 secs
Total no of threads: 10
Average time: 12.87653104
Decorated Threads total duration: 364.2767218
Decorated Average: 36.42767218
{'Average thread time': 1.0,
 'Total No of threads': 10,
 'Total sum': 364.2767218,
 'Worker_100000000': 127.1921616,
 'Worker_12800000': 37.0313439,
 'Worker_1600000': 9.3627994,
 'Worker_200000': 0.3208236,
 'Worker_25600000': 60.5957093,
 'Worker_3200000': 10.9247146,
 'Worker_400000': 0.9471039,
 'Worker_51200000': 94.57534310000001,
 'Worker_6400000': 20.8350688,
 'Worker_800000': 2.4916536000000002}

**python_config.allocator_backend = "mimalloc"**
**python_config.allocator_pymalloc_arena = True**
Total execution time: 118.8298634 secs
Total no of threads: 10
Average time: 11.882986339999999
Decorated Threads total duration: 330.2539567
Decorated Average: 33.02539567
{'Average thread time': 1.0,
 'Total No of threads': 10,
 'Total sum': 330.2539567,
 'Worker_100000000': 116.25883929999999,
 'Worker_12800000': 32.503140200000004,
 'Worker_1600000': 6.2709764,
 'Worker_200000': 0.48406330000000003,
 'Worker_25600000': 55.7040882,
 'Worker_3200000': 10.2861184,
 'Worker_400000': 0.7608446999999999,
 'Worker_51200000': 86.11589790000001,
 'Worker_6400000': 19.772016,
 'Worker_800000': 2.0979723}

Larger allocations ~27 GB
**System**
Total execution time: 239.5187612 secs
Total no of threads: 6
Average time: 39.91979353333333
Decorated Threads total duration: 529.5975608
Decorated Average: 88.26626013333333
{'Average thread time': 1.0,
 'Total No of threads': 6,
 'Total sum': 529.5975608,
 'Worker_100000000': 168.76296920000001,
 'Worker_1600000': 5.2320013,
 'Worker_200000000': 238.8294691,
 'Worker_400000': 2.3917918,
 'Worker_51200000': 98.48762980000001,
 'Worker_6400000': 15.893699599999998}

**snmalloc**
Total execution time: 218.7392619 secs
Total no of threads: 6
Average time: 36.45654365
Decorated Threads total duration: 491.53072060000005
Decorated Average: 81.92178676666667
{'Average thread time': 1.0,
 'Total No of threads': 6,
 'Total sum': 491.53072060000005,
 'Worker_100000000': 157.75468180000001,
 'Worker_1600000': 3.7927923999999997,
 'Worker_200000000': 217.52575180000002,
 'Worker_400000': 1.0537541000000001,
 'Worker_51200000': 96.0508364,
 'Worker_6400000': 15.3529041}

**snmalloc+global**
Total execution time: 217.99587250000002 secs
Total no of threads: 6
Average time: 36.33264541666667
Decorated Threads total duration: 485.4429698
Decorated Average: 80.90716163333333
{'Average thread time': 1.0,
 'Total No of threads': 6,
 'Total sum': 485.4429698,
 'Worker_100000000': 154.3180247,
 'Worker_1600000': 3.7139067,
 'Worker_200000000': 217.26522359999998,
 'Worker_400000': 1.4497356,
 'Worker_51200000': 94.18062259999999,
 'Worker_6400000': 14.5154566}

**Comment by ryancinsight** [comment]
Since the smaller allocations seem faster, I retested with [1600000 for i in range(200)] resulting in snmalloc being ~15% faster than system and pymalloc:

#system
Total execution time: 205.5070529 secs
Total no of threads: 200
Average time: 1.0275352645
Decorated Threads total duration: 2725.785295100002
Decorated Average: 13.628926475500009
{'Average thread time': 1.0,
 'Total No of threads': 200,
 'Total sum': 4.668408400000004,
 'Worker_1600000': 4.668408400000004}

#snmalloc
Total execution time: 176.258602 secs
Total no of threads: 200
Average time: 0.8812930099999999
Decorated Threads total duration: 2094.6775846999994
Decorated Average: 10.473387923499997
{'Average thread time': 1.0,
 'Total No of threads': 200,
 'Total sum': 6.799425899999989,
 'Worker_1600000': 6.799425899999989}

**Comment by SchrodingerZhu** [comment]
snmalloc should be ready now with version 0.2.25

**Comment by ryancinsight** [comment]
> This looks good. But is failing CI because it needs a newer version of the `snmalloc_sys` crate.
> 
> Also, I believe you'll want to rename the `ctx` argument to `_ctx` in the changed functions to prevent a compiler warning about unused arguments.
> 
> I guess I'll wait on the new crate version before this merged.
> 
> Thank you for following up and getting the snmalloc changes made upstream!

Corrections are now made, let me know if you would like anything further, best!

**Review by indygreg — APPROVED** [review]
This looks great!

The separate allocator backends for `raw` and `arena` is probably doable. I do get a little scared about mixing allocators because you can get in a situation where you `alloc()` with one but `free()` with another. If there is only a single allocator in play, that shouldn't be a problem. However, the pymalloc arena allocator already uses separate allocator/free functions, so maybe I'm just being paranoid.

While it feels like it could be a footgun, I think as long as we document the risks in the docs, it seems like a reasonable feature to expose.

**Pull request closed without merging**
