### PR TITLE
Use absolute exe path in pyembed.OxidizedPythonInterpreterConfig

### PR DESCRIPTION
**Pull request by gi0baro**
SSIA

This allows to keep correct paths for filesystem importer in case of symbolic linking built executables on all operative systems, as `std::env::current_exe` [might not return consistent results](https://doc.rust-lang.org/std/env/fn.current_exe.html#platform-specific-behavior).

### CODE REVIEW

**Review by indygreg — CHANGES_REQUESTED** [review]
Thank you for the contribution.

I wholeheartedly support the intent of this change.

However, there's an issue with this PR.

`canonicalize()` will yield a UNC path on Windows. If this path makes its way to CPython, it will likely have unintended consequences and break things. So we need to ensure we use a more traditional Windows path instead.

Unfortunately, Rust's standard library doesn't have a way to get a non-UNC symlink resolved absolute path. There are crates like `path-absolutize` and `path-dedot` that we could potentially use here. Although I'm unsure if they cover this exact case. So we may have to write a little bit extra code.

Also, if you want to add a test that the resolved path is not UNC, that would be appreciated. But it isn't required: this is something I can implement myself after this merges.

**Comment by gi0baro** [comment]
@indygreg I switched to [dunce](https://lib.rs/crates/dunce) which should quickly fix the Windows UNC thing.

CI is not passing on nightly, but it seems to be unrelated to this change.
Regarding tests: this is the early beginning of my Rust journey, then you can probably write such tests quickly and even properly compared to me.

**Comment by gi0baro** [comment]
@indygreg any chance to see this merged?

**Comment by indygreg** [comment]
> @indygreg any chance to see this merged?

I took a break from PyOxidizer for several weeks. I'm back to development and am slowly making my through open PRs. I should hopefully have feedback on this anywhere from a few minutes from now to a few days. I have to sort out dependencies between PRs and figure out which ones I want to tackle first.

**Review by indygreg — APPROVED** [review]
This looks great! Will push this to `main` shortly.

Thank you for your contribution!

**Pull request closed without merging**
